### ISSUE TITLE
PreMiD Fails to Launch - GPU Process Isn't Usable

### ISSUE THREAD

**Issue by dj-relax** [PreMiD/Linux#118]
Terminal output is as follows:

```
[relax@relax-laptop ~]$ premid
Gtk-Message: 07:59:31.641: Failed to load module "appmenu-gtk-module"
Opened socket
Socket connection
[34823:0222/075933.653731:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
[relax@relax-laptop ~]$
```

**Comment by dj-relax** [comment]
Issue solved, running with `--no-sandbox` allowed it to launch correctly.

**Comment by OverStyleFR** [comment]
It's work but i have this issue :

```
Socket connection
Error: Could not connect
    at Socket.onerror (/tmp/.mount_PreMiDt6Icm3/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Clear all activity
```
